

INSERT INTO industry (id, name) VALUES (1, 'Aerospace and Defense');
INSERT INTO industry (id, name) VALUES (2, 'Airlines');
INSERT INTO industry (id, name) VALUES (3, 'Diversified Financials');
INSERT INTO industry (id, name) VALUES (4, 'Commercial Banks');
INSERT INTO industry (id, name) VALUES (5, 'Construction and Farm Machinery');
INSERT INTO industry (id, name) VALUES (6, 'Wholesalers: Health Care');
INSERT INTO industry (id, name) VALUES (7, 'Food and Drug Stores');
INSERT INTO industry (id, name) VALUES (8, 'Food Consumer Products');
INSERT INTO industry (id, name) VALUES (9, 'Food Production');
INSERT INTO industry (id, name) VALUES (10, 'Health Care: Insurance and Managed Care');
INSERT INTO industry (id, name) VALUES (11, 'Insurance: Life, Health (mutual)');
INSERT INTO industry (id, name) VALUES (12, 'Insurance: Life, Health (stock)');
INSERT INTO industry (id, name) VALUES (13, 'Insurance: Property and Casualty (mutual)');
INSERT INTO industry (id, name) VALUES (14, 'Insurance: Property and Casualty (stock)');
INSERT INTO industry (id, name) VALUES (15, 'Mail, Package, and Freight Delivery');
INSERT INTO industry (id, name) VALUES (16, 'Motor Vehicles and Parts');
INSERT INTO industry (id, name) VALUES (17, 'Petroleum Refining');
INSERT INTO industry (id, name) VALUES (18, 'Pharmaceuticals');
INSERT INTO industry (id, name) VALUES (19, 'Specialty Retailers: Other');
INSERT INTO industry (id, name) VALUES (20, 'Telecommunications');
INSERT INTO industry (id, name) VALUES (21, 'Computers, Office Equipment');
INSERT INTO industry (id, name) VALUES (22, 'Computer Software');
INSERT INTO industry (id, name) VALUES (23, 'General Merchandisers');
INSERT INTO industry (id, name) VALUES (24, 'Information Technology Services');
INSERT INTO industry (id, name) VALUES (25, 'Internet Services and Retailing');


INSERT INTO company (id, industry_id, rank, name) VALUES (1, 17, 1, 'Exxon Mobil'); 
INSERT INTO company (id, industry_id, rank, name) VALUES (2, 7, 18, 'CVS Caremark'); 
INSERT INTO company (id, industry_id, rank, name) VALUES (3, 6, 14, 'McKesson'); 
INSERT INTO company (id, industry_id, rank, name) VALUES (4, 4, 16, 'J.P. Morgan Chase & Co.'); 
INSERT INTO company (id, industry_id, rank, name) VALUES (5, 7, 23, 'Kroger'); 
INSERT INTO company (id, industry_id, rank, name) VALUES (6, 9, 28, 'Archer Daniels Midland'); 
INSERT INTO company (id, industry_id, rank, name) VALUES (7, 12, 34, 'MetLife'); 
INSERT INTO company (id, industry_id, rank, name) VALUES (8, 19, 35, 'Home Depot'); 
INSERT INTO company (id, industry_id, rank, name) VALUES (9, 8, 41, 'PepsiCo'); 
INSERT INTO company (id, industry_id, rank, name) VALUES (10, 13, 43, 'State Farm Insurance Cos.'); 
INSERT INTO company (id, industry_id, rank, name) VALUES (11, 10, 45, 'WellPoint'); 
INSERT INTO company (id, industry_id, rank, name) VALUES (12, 3, 8, 'Fannie May'); 
INSERT INTO company (id, industry_id, rank, name) VALUES (13, 1, 39, 'Boeing'); 
INSERT INTO company (id, industry_id, rank, name) VALUES (14, 20, 49, 'Comcast'); 
INSERT INTO company (id, industry_id, rank, name) VALUES (15, 18, 57, 'Merck'); 
INSERT INTO company (id, industry_id, rank, name) VALUES (16, 1, 58, 'Lockheed Martin'); 
INSERT INTO company (id, industry_id, rank, name) VALUES (17, 17, 61, 'Sunoco'); 
INSERT INTO company (id, industry_id, rank, name) VALUES (18, 7, 63, 'Safeway'); 
INSERT INTO company (id, industry_id, rank, name) VALUES (19, 16, 67, 'Johnson Controls'); 
INSERT INTO company (id, industry_id, rank, name) VALUES (20, 15, 70, 'FedEx'); 
INSERT INTO company (id, industry_id, rank, name) VALUES (21, 18, 71, 'Abbott Laboratories'); 
INSERT INTO company (id, industry_id, rank, name) VALUES (22, 2, 76, 'United Continental Holdings'); 
INSERT INTO company (id, industry_id, rank, name) VALUES (23, 14, 84, 'Liberty Mutual Insurance'); 
INSERT INTO company (id, industry_id, rank, name) VALUES (24, 2, 83, 'Delta Air Lines'); 
INSERT INTO company (id, industry_id, rank, name) VALUES (25, 11, 86, 'New York Life Insurance'); 
INSERT INTO company (id, industry_id, rank, name) VALUES (26, 10, 89, 'Aetna'); 
INSERT INTO company (id, industry_id, rank, name) VALUES (27, 20, 90, 'Sprint Nextel'); 
INSERT INTO company (id, industry_id, rank, name) VALUES (28, 14, 93, 'Allstate'); 
INSERT INTO company (id, industry_id, rank, name) VALUES (29, 4, 95, 'American Express'); 
INSERT INTO company (id, industry_id, rank, name) VALUES (30, 5, 97, 'Deere'); 
INSERT INTO company (id, industry_id, rank, name) VALUES (31, 25, 56, 'Amazon.com'); 
INSERT INTO company (id, industry_id, rank, name) VALUES (32, 21, 17, 'Apple'); 
INSERT INTO company (id, industry_id, rank, name) VALUES (33, 4, 13, 'Bank of America Corp.'); 
INSERT INTO company (id, industry_id, rank, name) VALUES (34, 4, 20, 'Citigroup'); 
INSERT INTO company (id, industry_id, rank, name) VALUES (35, 16, 9, 'Ford Motor'); 
INSERT INTO company (id, industry_id, rank, name) VALUES (36, 24, 19, 'IBM'); 
INSERT INTO company (id, industry_id, rank, name) VALUES (37, 22, 37, 'Microsoft'); 
INSERT INTO company (id, industry_id, rank, name) VALUES (38, 4, 68, 'Morgan Stanley'); 
INSERT INTO company (id, industry_id, rank, name) VALUES (39, 23, 38, 'Target'); 
INSERT INTO company (id, industry_id, rank, name) VALUES (40, 4, 26, 'Wells Fargo'); 

